name: Terragrunt Workflow

on:
  workflow_dispatch:
    inputs:
      service_path:
        description: "Demo app workflows for Terraform"
        required: true
        default: ""
      action:
        description: "Choose between apply or destroy"
        required: true
        type: choice
        options:
          - apply
          - destroy

jobs:
  terragrunt:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Install Terragrunt
        run: |
          curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.0/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      - name: Initialize with Terragrunt (Including External Dependencies)
        run: |
          terragrunt run-all init --terragrunt-non-interactive --terragrunt-working-dir=${{ github.event.inputs.service_path }}

      - name: Plan with Terragrunt (Including External Dependencies)
        id: plan
        run: |
          terragrunt run-all plan --terragrunt-non-interactive --terragrunt-working-dir=${{ github.event.inputs.service_path }}

      - name: Apply Resources with Terragrunt (Including External Dependencies)
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          terragrunt run-all apply -auto-approve --terragrunt-non-interactive --terragrunt-working-dir=${{ github.event.inputs.service_path }}

      - name: Destroy Resources with Terragrunt (Including External Dependencies)
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          terragrunt run-all destroy -auto-approve --terragrunt-non-interactive --terragrunt-working-dir=${{ github.event.inputs.service_path }}
